# ===============================
# SERVER CONFIG
# ===============================
server.port=8081

# ===============================
# POSTGRESQL CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/GitLogChecks
spring.datasource.username=postgres
spring.datasource.password=Himanshu@142002
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# LOGGING (IMPORTANT FOR WEBHOOK DEBUG)
# ===============================
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ===============================
# WEBHOOK TESTING
# ===============================
spring.mvc.log-request-details=true

# ===============================
# CUSTOM (FOR GITHUB SECRET LATER)
# ===============================
github.webhook.secret=Himanshu

# ===============================
# GEMINI KEY FOR REVIEW
# ===============================
gemini.api.key=AIzaSyBAan1YKLSSvAtCpIzAoK2ZvEI7TRDB-1M